createLabels:
  - name: Working on it
    description: Working on it
    color: '#01AEEB'
  - name: Pull Request
    description: Pull Request
    color: '#01AEEB'
  - name: Resolved
    description: Resolved
    color: '#01AEEB'

onReviewPending:
  remove:
    - Working on it
    - Resolved
  set:
    - Pull Request

onOpen:
  remove:
    - Resolved
    - Working on it
  set:
    - Pull Request

onComment:
  remove:
    - Pull Request
    - Resolved
  set:
    - Working on it

onChangeRequest:
  remove:
    - Resolved
    - Pull Request
  set:
    - Working on it
