createLabels:
  - name: Working on it
    description: Working on it
    color: 01AEEB
  - name: Pull Request
    description: Pull Request
    color: 01AEEB
  - name: Resolved
    description: Resolved
    color: 01AEEB

onReviewPending:
  remove:
    - Working on it
    - Resolved
  set:
    - Pull Request

onClose:
  remove:
    - Resolved
    - Pull Request
  set:
    - Working on it

onOpen:
  remove:
    - Resolved
    - Working on it
  set:
    - Pull Request
    
onMerge:
  remove:
    - Working on it
    - Pull Request
  set:
    - Resolved

onComment:
  remove:
    - Pull Request
    - Resolved
  set:
    - Working on it

onChangeRequest:
  remove:
    - Resolved
    - Pull Request
  set:
    - Working on it
