onComment:
  remove:
    - Approved
    - Changes Requested
  set:
    - Comment

onApproved:
  remove:
    - Comment
    - Changes Requested
  set:
    - Approved

onChangesRequested:
  remove:
    - Commented
    - Approved
  set:
    - Changes Requested

onOpen:
  set:
    - Open

onMerge:
  set:
    - Merged

onClose:
  set:
    - Closed
