onComment:
  remove:
    - Approved
    - Changes Requested
  set:
    - Comment
    
onOpen:
  set:
    - Open
    
onMerge:
  set:
    - Merged
    
onClose:
  set:
    - Closed

onApproved:
  remove:
    - Comment
    - Changes Requested
  set:
    - Approved

onChangesRequested:
  remove:
    - Comment
    - Approved
  set:
    - Changes Requested
