createLabels:
  - name: Working on it
    description: Approved
    color: '#01AEEB'
  - name: Pull Request
    description: Approved
    color: '#01AEEB'
  - name: Resolved
    description: Approved
    color: '#01AEEB'
  - name: Failed
    description: Failed
    color: '#01AEEB'

onComment:
  remove:
    - Failed
    - Pull Request
    - Resolved
  set:
    - Working on it

onApprove:
  remove:
    - Failed
    - Working on it
    - Pull Request
  set:
    - Resolved

onChangeRequest:
  remove:
    - Failed
    - Approved
    - Pull Request
  set:
    - Working on it

onOpen:
  set:
    - Pull Request

onMerge:
  remove:
    - Failed
    - Working on it
    - Pull Request
  set:
    - Resolved

onClose:
  remove:
    - Working on it
    - Pull Request
    - Resolved
  set:
    - Failed
