onComment:
  remove:
    - Approved
    - Changes Requested
  set:
    - Comment

onApprove:
  remove:
    - Comment
    - Changes Requested
  set:
    - Approved

onChangeRequest:
  remove:
    - Comment
    - Approved
  set:
    - Changes Requested

onOpen:
  set:
    - Open

onMerge:
  remove:
    - Open
    - Comment
    - Approved
    - Changes Requested
  set:
    - Merged

onClose:
  remove:
    - Open
    - Comment
    - Approved
    - Changes Requested
  set:
    - Closed
