createLabels:
- name: Approved
  description: Approved
  color: '#01AEEB'
- name: Changes Requested
  description: Approved
  color: '#01AEEB'
- name: Comment
  description: Approved
  color: '#01AEEB'
- name: Open
  description: Open
  color: '#01AEEB'
- name: Closed
  description: Closed
  color: '#01AEEB'
 - name: Merged
  description: Merged
  color: '#01AEEB'

onComment:
  remove:
    - Approved
    - Changes Requested
  set:
    - Comment

onApprove:
  remove:
    - Comment
    - Changes Requested
  set:
    - Approved

onChangeRequest:
  remove:
    - Comment
    - Approved
  set:
    - Changes Requested

onOpen:
  set:
    - Open

onMerge:
  remove:
    - Open
    - Comment
    - Approved
    - Changes Requested
  set:
    - Merged

onClose:
  remove:
    - Open
    - Comment
    - Approved
    - Changes Requested
  set:
    - Closed
