onComment:
  remove:
    - Approved
    - Changes Requested
  set:
    - Comment

onApproved:
  remove:
    - Comment
    - Changes Requested
  set:
    - Approved

onChangesRequested:
  remove:
    - Comment
    - Approved
  set:
    - Changes Requested
