name: estrada9166/labeler

on: [pull_request_review, pull_request_review_comment]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Labeler
        uses: estrada9166/labeler
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CONFIG_PATH: labeler-config.yml
