name: pull-request-labeler

on: [pull_request, pull_request_review, pull_request_review_comment]

jobs:
  pull-request-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Workflow PR Labeler
        uses: igoroctaviano/workflow-pr-labeler@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CONFIG_PATH: labeler-config.yml
